
os: linux

language: cpp
services:
  - docker

before_install:

  # appimagetool
  - wget -nv -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O appimagetool.AppImage

script:

  # debian buster
  - docker build . -f deploydocker/Dockerfile.winedeploy.debian -t wine-appimage.debian

after_success:
  - mkdir apps

  # debian buster
  - docker run --rm -v $(pwd)/apps:/tmp/apps -ti wine-appimage.debian cp wine-i386-debian.AppImage /tmp/apps

  # uploadtool
  - ls -lh apps/* # Assuming you have some files in out/ that you would like to upload
  - wget -c https://github.com/probonopd/uploadtool/raw/master/upload.sh
  - bash upload.sh apps/*

branches:
  except:
    - # Do not build tags that we create when we upload to GitHub Releases
    - /^(?i:continuous.*)$/
    - /^release[0-9a-z\-]*/
