#!/bin/bash
HERE="$(dirname "$(readlink -f "${0}")")"

export LD_LIBRARY_PATH="$HERE/usr/lib":$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="$HERE/usr/lib/i386-linux-gnu":$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="$HERE/lib":$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="$HERE/lib/i386-linux-gnu":$LD_LIBRARY_PATH

# Sound Library
export LD_LIBRARY_PATH="$HERE/usr/lib/i386-linux-gnu/pulseaudio":$LD_LIBRARY_PATH
export LD_LIBRARY_PATH="$HERE/usr/lib/i386-linux-gnu/alsa-lib":$LD_LIBRARY_PATH

# libGL drivers
export LIBGL_DRIVERS_PATH="$HERE/usr/lib/i386-linux-gnu/dri":$LIBGL_DRIVERS_PATH

# Font Config
export FONTCONFIG_PATH="$HERE/etc/fonts"

# LD
export WINELDLIBRARY="$HERE/lib/ld-linux.so.2"

# Workaround for: wine: loadlocale.c:129: _nl_intern_locale_data:
# Assertion `cnt < (sizeof (_nl_value_type_LC_TIME) / sizeof (_nl_value_type_LC_TIME[0]))' failed.
export LC_ALL=C LANGUAGE=C LANG=C

# Wine env
export WINEVERPATH=${WINEVERPATH:-"$HERE"}
export PATH=${WINEVERPATH}/bin:$PATH 
export WINESERVER=${WINEVERPATH}/bin/wineserver
export WINELOADER=${WINEVERPATH}/bin/wine
export WINEDLLPATH=${WINEVERPATH}/lib/wine/fakedlls
export WINEARCH=win32
export WINEPREFIX=${WINEPREFIX:-"$HOME/.wine"}
export WINEDEBUG=${WINEDEBUG:-"fixme-all"}
export WINEESYNC=${WINEESYNC:-"0"}

# DXVK env
export DXVK_HUD=${DXVK_HUD:-"1"}
export DXVK_LOG_LEVEL=${DXVK_LOG_LEVEL:-"none"}

#
# FIXME: find better workaround for this.
#
# Load vulkan icd files as per vendor
#
checkdri=$(cat /var/log/Xorg.0.log | grep -e "DRI driver:" | awk '{print $8}')

if [ "$checkdri" = "i965" ]; then
    export VK_ICD_FILENAMES=${VK_ICD_FILENAMES:-"$HERE/usr/share/vulkan/icd.d/intel_icd.i686.json"}
elif [ "$checkdri" = "radeonsi" ]; then
    export VK_ICD_FILENAMES=${VK_ICD_FILENAMES:-"$HERE/usr/share/vulkan/icd.d/radeon_icd.i686.json"}
fi

LD_PRELOAD="$HERE/bin/libhookexecv.so" "$WINELDLIBRARY" "$HERE/bin/wine" "$@" | cat
