name: CI


on: 
  release:
    [released]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - run: wget -nv -c "https://github.com/AppImage/AppImageKit/releases/download/continuous/appimagetool-x86_64.AppImage" -O appimagetool.AppImage

      - run: docker build . -f deploydocker/Dockerfile.winedeploy.debian -t wine-appimage.debian
      
      - run: mkdir apps
      - run: docker run -v $(pwd)/apps:/tmp/apps wine-appimage.debian cp wine-i386-debian.AppImage /tmp/apps
      - run: ls -lh apps/*

      - name: get upload url
        id: get_upload_url
        run: |
          url=$(echo "$response" | jq -r '.upload_url')
          echo "::set-output name=url::$url"
        env: 
          response:  ${{ steps.get_latest_release.outputs.data }}
     
      - name: Upload a Release Asset
        uses: actions/upload-release-asset@v1.0.2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          # The URL for uploading assets to the release
          upload_url:  ${{steps.get_upload_url.outputs.url}}
          # The path to the asset you want to upload
          asset_path: apps/wine-i386-debian.AppImage
          # The name of the asset you want to upload
          asset_name: wine-i386-debian.AppImage
          # The content-type of the asset you want to upload. See the supported Media Types here: https://www.iana.org/assignments/media-types/media-types.xhtml for more information
          asset_content_type: application/zip
